media:
  input: public/img
  output: /img
content:
  - name: blog
    label: Blog
    type: collection
    path: src/pages/blog
    fields:
      - name: layout
        label: Layout
        type: string
        default: ../../layouts/BlogLayout.astro
        required: true
      - name: title
        label: Title
        required: true
      - name: description
        label: Description
        required: true
      - name: image
        label: Image
        type: string
      - name: pubDate
        label: Date published
        type: string
        required: true
      - name: context
        label: Context
      - name: series
        label: Series
      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
    extension: mdx
    filename: '{year}-{month}-{day}-{primary}.mdx'
    view:
      fields: [ layout, title, description, image, pubDate, context, series ]
      primary: title
      sort: [ title, date ]
      default:
        search: ''
        sort: title
        order: desc